[package]
name = "monarch-client"
version = "0.1.0"
authors = ["David Ayeke"]
edition = "2018"

[dependencies]
monarch = {path = "../monarch"}

[dependencies.amethyst]
version = "0.11"
features = ["metal", "nightly"]